### PR TITLE
Add files for infrastructure tutorials

### PR DESCRIPTION
**Pull request by tathey1**
Could be useful for onboarding new lab members?

### CODE REVIEW

**Review by pythonLoader — CHANGES_REQUESTED** [review]
I think we should put it under the directory lab_tutorials/sysadmin? And name the file creating_user_accounts_guide.md. What do you think?

**Comment by tathey1** [comment]
> I think we should put it under the directory lab_tutorials/sysadmin? And name the file creating_user_accounts_guide.md. What do you think?

I like the `sysadmin` subdirectory idea, and making the title more informative. But how about the making the goal of the document to talk about ccg-gpu as a whole? I named it `ccg-gpu_guide` now.

**Review by Lin-K76 — APPROVED** [review]
Looks good to me!

**Review by pythonLoader — APPROVED** [review]
Looks good now!

**Pull request merged**
